# Generated by Django 4.2 on 2023-04-08 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_produto_imagem'),
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name_plural': 'Carrinho'},
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='produtos_carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produto'),
        ),
    ]
