# Generated by Django 4.2 on 2023-04-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
